@SocialMedia_HostAddress = https://localhost

GET {{SocialMedia_HostAddress}}/api/user
Accept: application/json

###

POST {{SocialMedia_HostAddress}}/api/user
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "UserName": "john.doe",
  "password": "john1234"
}

###

GET {{SocialMedia_HostAddress}}/api/post
Accept: application/json
