@SocialMedia_HostAddress = https://localhost

GET {{SocialMedia_HostAddress}}/api/user
Accept: application/json

###

POST {{SocialMedia_HostAddress}}/api/account/register
Content-Type: application/json

{
  "name": "Emanuil",
  "email": "emanuil@example.com",
  "UserName": "emanuill",
  "password": "john1234"
}

###

GET {{SocialMedia_HostAddress}}/api/post
Accept: application/json

###

POST {{SocialMedia_HostAddress}}/api/account/login
Content-Type: application/json

{
  "email": "emanuel@gmail.com",
  "UserName": "emanuel.marques",
  "password": "emanuel123"
}

